### ISSUE TITLE
Should talpa.ai be filtered?

### ISSUE THREAD

**Issue by ngoomie** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#47]
talpa.ai is a book search tool that makes use of ChatGPT on the backend, letting you search for books by describing what you remember about them -- it has some example searches on the homepage. It checks against LibraryThing's database to make sure the books actually exist, so there's no risk of hallucinated books showing up in searches. I think it's actually a pretty solid tool, a rare good usage of machine learning tech post-AI boom, and it doesn't seem like the sort of thing likely to shit up search results necessarily? But at the same time I do wonder if it might be good to potentially include for people who really, seriously, do not want to see any AI _anything_. Though I guess too that's kinda what the point of the nuclear list is, and I'd imagine this would be filtered out by that.

**Comment by laylavish** [comment]
While I understand that talpa.ai is definitely different in scope to that of generative image AI's or typical chatbot llm's, and doesn't hallucinate or technically do any harm towards creatives, it's still backed by unethical models from both Anthropic & Open AI, whose models are affecting the internet and individuals at large. For now, I'll put it in the nuclear list, but there's a chance it might get put in the main list because Anthropic and Open AI are just so devious.

**Comment by ngoomie** [comment]
Yeah I was quite disappointed when I realized Talpa was utilizing OpenAI for exactly the reasons you mentioned, which was actually part of why I figured it may be a good idea to suggest it in some form.

**Comment by laylavish** [comment]
Yeah, it's sad. Thanks for the suggestion, though! I'm gonna to close this issue now, since we've already discussed what should happen here.
