### ISSUE TITLE
A website for the list

### ISSUE THREAD

**Issue by Derkades** [laylavish/uBlockOrigin-HUGE-AI-Blocklist#78]
`nucleovisual [dot] com`

Contains thousands of articles with false information. Some articles start with "Sure, here is your article:" or similar.

**Comment by TPS** [comment]
`polyai.ai` is unblocked image generation.  Worth blocking `.ai^`?

**Comment by laylavish** [comment]
Both are added. I don't think it's worth just blocking .ai tld itself. All .ai is a domain. It can be used for AI projects/products (which a lot of them gravitate towards using .ai) but it can be used for non ai applications. It's kinda funny, because .ai is actually a country code tld for Anguilla, and it's being a bit misused for the purposes of AI products, which is a little sad.
